### PR TITLE
Modify RepleBacklogsize config from 10GB to 100MB

### PR DESCRIPTION
**Pull request by qiuyesuifeng**

### CODE REVIEW

**Comment by siddontang** [comment]
I think 1mb is ok, 100mb is huge for test.

**Comment by qiuyesuifeng** [comment]
ok, got it

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
I am confused, is  backlog in disk or in memory?

**Comment by siddontang** [comment]
Backlog can be set in disk or in memory like redis. 

Default is memory.

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
