### PR TITLE
Fix set value empty bug

### PR DESCRIPTION
**Pull request by qiuyesuifeng**
Fix empty value get/set bug. 
For example,
set a "" should return "OK"
get a should return ""
also include mget/mset cmd

### CODE REVIEW

**Comment by siddontang** [comment]
I think you should close this pr now. 

Redis support empty key, so we should support it too.

**Comment by siddontang** [comment]
Maybe you can add empty value test for replication too.

**Comment by qiuyesuifeng** [comment]
yeah,  got it, i will add a simple test case in this version at once.

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
