### PR TITLE
Using juju/errors instead of reborn/go/errors

### PR DESCRIPTION
**Pull request by qiuyesuifeng**
Notice
“errors.Equal(err, io.EOF)”
changed to
“errors.Cause(err) == io.EOF”
is ok？

### CODE REVIEW

**Comment by ngaut** [comment]
@qiuyesuifeng   Are there any tests for the usage of juju?

**Comment by qiuyesuifeng** [comment]
Ok, i will add a test case to check it.

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
