### PR TITLE
remove unnecessary len(args) check

### PR DESCRIPTION
**Pull request by qiuyesuifeng**

### CODE REVIEW

**Comment by ngaut** [comment]
Any reason why remove it ?

**Comment by siddontang** [comment]
We will do the same thing in inner store api.

**Comment by qiuyesuifeng** [comment]
yeah, store layer func has done the same thing, so service checking maybe not need.

**Comment by ngaut** [comment]
Gotcha

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
